# Generated by Django 4.2.17 on 2025-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name="Afficher sur la page d'accueil"),
        ),
    ]
