# Generated by Django 5.0.9 on 2025-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_brand_foreign_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Modèle', 'verbose_name_plural': 'Modèles'},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du modèle'),
        ),
    ]
