# Generated by Django 5.0.9 on 2025-11-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_type_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.brand', verbose_name='Marque'),
        ),
    ]
