# Generated by Django 5.0.9 on 2025-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_brand_to_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_essential',
            field=models.BooleanField(default=False, verbose_name='Sous-catégorie essentielle'),
        ),
    ]
