# Generated by Django 5.0.9 on 2025-11-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_subcategory_is_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_ad_slider',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le slider de publicité'),
        ),
    ]
