# Generated by Django 5.0.9 on 2025-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_show_in_ad_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_ad_slider',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le slider de publicité'),
        ),
    ]
