# Generated by Django 5.0.9 on 2025-11-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_show_in_ad_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre affiché sur le slide', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description affichée sur le slide', verbose_name='Description')),
                ('slide_type', models.CharField(choices=[('category', 'Catégorie'), ('subcategory', 'Sous-catégorie'), ('product', 'Produit')], max_length=20, verbose_name='Type de slide')),
                ('custom_image', models.ImageField(blank=True, help_text="Laissez vide pour utiliser l'image du produit/catégorie", null=True, upload_to='hero_slides/', verbose_name='Image personnalisée')),
                ('order', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour masquer temporairement', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='shop.category', verbose_name='Catégorie')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='shop.product', verbose_name='Produit')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='shop.subcategory', verbose_name='Sous-catégorie')),
            ],
            options={
                'verbose_name': 'Slide Hero',
                'verbose_name_plural': 'Slides Hero',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
