# Generated by Django 5.0.9 on 2025-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text='Titre affiché sur le slide (optionnel)', max_length=200, verbose_name='Titre'),
        ),
    ]
