# Generated by Django 4.2.27 on 2025-12-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_make_heroslide_title_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.collection', verbose_name='Collection'),
        ),
    ]
