# Generated by Django 4.2.27 on 2025-12-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url_field',
            field=models.URLField(blank=True, verbose_name='Logo (URL externe)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo (Upload)'),
        ),
    ]
