# Generated by Django 4.2.27 on 2025-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_brand_logo_url_field_alter_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_url_field',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='website',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL directe de l'image du logo", max_length=500, verbose_name='URL du Logo'),
        ),
    ]
