# Generated by Django 4.2.27 on 2025-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_brand_logo_url_field_remove_brand_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Dimension recommandee: 200x200 px (carre). Logo affiche dans un cercle. Format: PNG transparent ou WebP < 50KB', null=True, upload_to='brands/', verbose_name='Logo (Upload)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL directe de l'image du logo (même dimension: 200x200 px carré)", max_length=500, verbose_name='URL du Logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimension recommandee: 800x320 px (ratio 2.5:1 paysage). Format: WebP/JPG < 100KB', null=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimension recommandee: 600x600 px (carre). Format: WebP/JPG < 100KB', null=True, upload_to='collections/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='custom_image',
            field=models.ImageField(blank=True, help_text="Dimension recommandee: 1200x500 px (ratio 2.4:1 banniere). Mobile: image centree. Format: WebP/JPG < 150KB. Laissez vide pour utiliser l'image du produit/categorie", null=True, upload_to='hero_slides/', verbose_name='Image personnalisee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Dimension recommandee: 600x600 px (carre 1:1). Fond blanc. Format: WebP/JPG < 100KB', null=True, upload_to='products/', verbose_name='Image principale (deprecated)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Dimension recommandee: 600x600 px (carre 1:1). Fond blanc prefere. Format: WebP/JPG < 100KB', upload_to='products/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimension recommandee: 400x450 px (ratio 1:1 carre/portrait). Pour CreativeBackground et SubcategoryShowcase. Format: WebP/JPG < 80KB', null=True, upload_to='subcategories/', verbose_name='Image'),
        ),
    ]
